# Generated by Django 4.1.4 on 2022-12-19 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentmodel_address_studentmodel_admissiondate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('trno', models.IntegerField(unique=True)),
                ('dept', models.CharField(max_length=50)),
                ('edu', models.CharField(max_length=50)),
                ('mob', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('post', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='teachesub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subjectmodel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.teachermodel')),
            ],
        ),
    ]
