# Generated by Django 4.1.4 on 2022-12-20 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_teachermodel_mob_teachermodel_mobno'),
    ]

    operations = [
        migrations.CreateModel(
            name='webMarksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('It1', models.IntegerField()),
                ('It2', models.IntegerField()),
                ('It3', models.IntegerField()),
                ('semend', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='osMarksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('It1', models.IntegerField()),
                ('It2', models.IntegerField()),
                ('It3', models.IntegerField()),
                ('semend', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DBMSMarksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('It1', models.IntegerField()),
                ('It2', models.IntegerField()),
                ('It3', models.IntegerField()),
                ('semend', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DBMSlMarksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('It1', models.IntegerField()),
                ('It2', models.IntegerField()),
                ('It3', models.IntegerField()),
                ('semend', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmodel')),
            ],
        ),
    ]
