# Generated by Django 4.1.4 on 2022-12-20 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_webmarksmodel_osmarksmodel_dbmsmarksmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='marksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('It1', models.IntegerField()),
                ('It2', models.IntegerField()),
                ('It3', models.IntegerField()),
                ('semend', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subjectmodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='dbmsmarksmodel',
            name='student',
        ),
        migrations.RemoveField(
            model_name='osmarksmodel',
            name='student',
        ),
        migrations.RemoveField(
            model_name='webmarksmodel',
            name='student',
        ),
        migrations.DeleteModel(
            name='DBMSlMarksModel',
        ),
        migrations.DeleteModel(
            name='DBMSMarksModel',
        ),
        migrations.DeleteModel(
            name='osMarksModel',
        ),
        migrations.DeleteModel(
            name='webMarksModel',
        ),
    ]
